Problem Description
Given a string A, find if there is any subsequence that repeats itself.

A subsequence of a string is defined as a sequence of characters generated by deleting some characters in the string without changing the order of the remaining characters.

NOTE:
1. Subsequence length should be greater than or equal to 2.
2. The repeating subsequence should be disjoint that is no index in the original subsequence should be present in the repeated subsequence.



Problem Constraints
1 <= length(A) <= 100



Input Format
The first and the only argument of input contains a string A.



Output Format
Return an integer, 1 if there is any subsequence which repeat itself else return 0.



Example Input
Input 1:

 A = "abab"
Input 2:

 A = "abba"


Example Output
Output 1:

 1
Output 2:

 0


Example Explanation
Explanation 1:

 "ab" is repeated.
Explanation 2:

 There is no repeating subsequence.
   
   
   
   
   
   
   
   
   
   public class Solution {
    public int anytwo(String A) {
        
        int n=A.length();
        
        int[][]dp=new int[n+1][n+1];
        
        
        for(int i=0;i<n;i++){
            
            
            for(int j=0;j<n;j++){
                
                
                if(A.charAt(i)==A.charAt(j)  && i!=j){
                    
                    dp[i+1][j+1]=1+dp[i][j];
                }
                
                else{
                    dp[i+1][j+1]=Math.max(dp[i][j+1], dp[i+1][j]);
                }
            }
        }
        
        return dp[n][n]>=2?1:0;
    }
}
